name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  IMAGE_NAME: ikuku1010/epl-poll-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate version tag
      run: |
        COUNT=$(git rev-list --count HEAD)
        VERSION="v0.1.$COUNT"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "$VERSION" > version.txt
        echo "Generated version: $VERSION"

    - name: Log in to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and tag Docker image
      run: |
        docker build -t $IMAGE_NAME:$VERSION .

    - name: Push Docker image
      run: |
        docker push $IMAGE_NAME:$VERSION

    - name: Update Helm values file
      run: |
        sed -i "s|\(tag:\s*\).*|\1$VERSION|" helm/eplteams-polling/values.yaml

    - name: Commit and push updated values.yaml to main
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add helm/eplteams-polling/values.yaml
        git commit -m "chore: update image tag to $VERSION" || echo "No changes to commit"
        git push origin main
